# Jenkins Docker Setup for DemoQA Project

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: demoqa-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    networks:
      - jenkins-network

  # Optional: Jenkins agent with tools pre-installed
  jenkins-agent:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: demoqa-jenkins-agent
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - jenkins
    networks:
      - jenkins-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
